version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14      
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  seleniumscript:
    image: sujithsukumaran/seleniumdocker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=testng.xml
    volumes:
      - ./output/test-result:/usr/folder/practice/test-output
